# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update index.html

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        architecture: 'x64'
    
    - name: Update overview
      run: |
        python --version
        python main.py
        
    - name: Commit new index.html
      run: |
        git config --global user.name 'tanjeffreyz.github.io'
        git config --global user.email 'tanjeffreyz.github.io@tanjeffreyz.github.io'
        git add * || true
        git commit -m 'Updated index.html' || true
        git push
        git push -f origin main:github-pages
